Repository VirtoCommerce/vc-module-customer-export-import, pull requests merged in 2021-07, with the labels that each got.

#42 VDS-1995 Solve problems with updating two membres by one import record.
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedOrganizationDataImporter.cs
Labels: deploy-demo

#44 VDS-2060: Add validation and error messages for account
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
Labels: deploy-qa

#46 VDS-2058 Implement the accounts creating logic at the contacts import
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
Labels: deploy-qa

#47 VDS-2062: Password set & validate
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAccountValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/FakeSignInManager.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/FakeUserManager.cs
Labels: deploy-qa

#48 VDS-2063: Generate password
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/IPasswordGenerator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CryptoRandom.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/PasswordGenerator.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
Labels: deploy-demo, deploy-qa

#51 VDS-1544, VDS-1537: Add permissions for customers Export and Import
  src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
Labels: deploy-demo, deploy-qa

#49 VDS-2248, VDS-1906: Safe parse & add address type default value
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAddressValidator.cs
Labels: deploy-demo, deploy-qa

#50 VDS-2297: Fix rows order in error report
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
Labels: deploy-qa

#53 VDS-2252 Show exceptions details at import
  src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/export-processing.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
Labels: deploy-demo
