Repository VirtoCommerce/vc-module-customer-export-import, pull requests merged in 2021-06, with the labels that each got.

#23 VDS-1851: Remove "s" in the word "Files" in Import/Export Contact blade.
  src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
Labels: deploy-demo, deploy-qa

#30 VDS-1360: Development import statistics for UI
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportPushNotification.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerImportReporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ImportPushNotificationExtensions.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ValidationExtensions.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportReporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntitiesAreNotDuplicatesValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntityIsNotDuplicateValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Content/css/customer-export-import.css
  src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/dialogs/customerImport-dialog.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/resources/import.js
Labels: deploy-demo, deploy-qa

#32 VDS-1299: Fix empty fields splitting
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
Labels: deploy-demo, deploy-qa

#34 VDS-1593 Implement backend for organizations import preview
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataPreview.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataPreviewRequest.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportDataValidationRequest.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerDataValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICustomerImportPagedDataSource.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICustomerImportPagedDataSourceFactory.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerDataValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportHelper.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedCustomerDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSource.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerImportPagedDataSourceFactory.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.tpl.html
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerImportPagedDataSourceTests.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/TestHelper.cs
Labels: deploy-qa

#35 VDS-1883: Implement closing preview blade if new file upload
  src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/file-upload.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/dialogs/customerDeleteAndClose-dialog.tpl.html
Labels: deploy-demo, deploy-qa

#38 VDS-1313 VDS-1334 implement organizations import
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvPagedCustomerDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerDataValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedOrganizationDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportOrganizationsValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/BackgroundJobs/ImportJob.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
Labels: deploy-qa

#40 VDS-2037 VDS-2036 Add missed column and not closed quote cases handeling
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
Labels: review task created

#39 VDS-1366: Log validation errors
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvMember.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableOrganization.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableContact.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Models/ImportableOrganization.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/ModuleConstants.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/Services/ICsvCustomerImportReporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Core/VirtoCommerce.CustomerExportImportModule.Core.csproj
  src/VirtoCommerce.CustomerExportImportModule.Data/ExportImport/GenericClassMap.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Helpers/ValidationExtensions.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerDataValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvCustomerImportReporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedContactDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CsvPagedOrganizationDataImporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerDataExporter.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Services/CustomerExportPagedDataSource.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportAddressValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportContactsValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportDynamicPropertiesValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportDynamicPropertyValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportEntityIsNotDuplicateValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportMemberValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportOrganizationValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/Validation/ImportOrganizationsValidator.cs
  src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
  src/VirtoCommerce.CustomerExportImportModule.Web/Controllers/Api/ImportController.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Localizations/en.VirtoCommerce.CustomerExportImport.json
  src/VirtoCommerce.CustomerExportImportModule.Web/Module.cs
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-preview.js
  src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/dialogs/customerImport-dialog.tpl.html
  src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvMemberValidationTests.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerExportPagedDataSourceTests.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/CustomerImportPagedDataSourceTests.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/FakeSignInManager.cs
  tests/VirtoCommerce.CustomerExportImportModule.Tests/FakeUserManager.cs
Labels: deploy-demo, deploy-qa
